pipeline {
    agent { label 'cpp-agent' }

    parameters {
        booleanParam(name: 'SKIP_CHECKS_AND_TESTS', defaultValue: false, description: 'Marque esta opção para um build rápido que apenas gera o artefato, pulando as verificações de código e os testes.')
    }

    triggers {
        cron('H 0 * * *') 
    }

    environment {
        ARTIFACT_NAME = 'calculator'
        ARTIFACT_PATH = "src/bin/${ARTIFACT_NAME}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Code Check') {
            when {
                expression { return params.SKIP_CHECKS_AND_TESTS == false }
            }
            steps {
                sh 'make check'
            }
        }

        stage('Build') {
            steps {
                sh 'make'
            }
        }

        stage('Test') {
            when {
                expression { return params.SKIP_CHECKS_AND_TESTS == false }
            }
            steps {
                sh 'make unittest'
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: env.ARTIFACT_PATH, followSymlinks: false
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
            cleanWs()
        }
    }
}