jenkins:
  systemMessage: "Jenkins configurado via JCasC por Eduardo - Desafio Philips DevOps"
  mode: NORMAL
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USERNAME}
          password: ${JENKINS_ADMIN_PASSWORD}
        - id: ${JENKINS_AGENT_USERNAME}
          password: ${JENKINS_AGENT_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: admin
            permissions: 
              - Overall/Administer
            entries: 
              - user: ${JENKINS_ADMIN_USERNAME}
          - name: agent
            permissions: 
              - Overall/Read
              - Agent/Connect
              - Agent/Disconnect
              - Agent/Build
            entries: 
              - user: ${JENKINS_AGENT_USERNAME}

  nodes:
    - permanent:
        name: agent1
        launcher: inbound
        labelString: "cpp-agent"
        remoteFS: /home/jenkins/agent
    - permanent:
        name: agent2
        launcher: inbound
        labelString: "cpp-agent"
        remoteFS: /home/jenkins/agent

jobs:
  - script: |
      multibranchPipelineJob('Test_DevOps_Multibranch_Pipeline') {
        branchSources {
          github {
            id('Test_DevOps_Pipeline')
            repoOwner('NavesEdu')
            repository('Test_DevOps')
          }
        }
        
        factory {
          workflowBranchProjectFactory {
            scriptPath('Jenkinsfile') 
          }
        }

        configure { node ->
          node / 'triggers' << 'com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger'{
            // Configura o Job Multibranch para escanear a cada 15 minutos (por exemplo)
            interval('15m')
          }

          def traits = node / sources / data / 'jenkins.branch.BranchSource' / source / traits
          traits << 'org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait' {
            strategyId(3) // 3 = Descobrir branches padrão e feature
          }
        }
      }

unclassified:
  location:
    adminAddress: ${JENKINS_ADMIN_EMAIL}
    url: http://localhost:8080/

  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
